services:
  date:
    image: fillinius/servicedatenow
    build:
      dockerfile: date.dockerfile
  result:
    image: fillinius/frontops
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - date
